version: "3.9"

services:
  wishingwell-db:
    image: postgres:15.1-alpine
    container_name: wishingwell-database
    restart: always
    volumes:
#      - ./data:/var/lib/postgresql/data
      - ./data/01-schema.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./data/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PSW}
    ports:
      - "5432:5432"